---
## Update Network Config via Netplan
- name: Copy network config
  template:
    src: files/01-netcfg.yaml.j2 
    dest: /etc/netplan/new-netconf.yaml
- name: Apply netplan
  command: netplan apply
  async: 45
  poll: 0